using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.SceneManagement;
using Vuforia;
using UnityEngine.UI;
using UnityEngine.Video;

public class ReloadScene : MonoBehaviour {

	// Use this for initialization
	void Start () {
		
	}
	
	// Update is called once per frame
	void Update () {
		
	}

	public void reloadScene () {

		FindRootObject ("ARCamera").GetComponent<VuforiaBehaviour> ().enabled = false;
		FindRootObject ("ARCamera").SetActive (false);
		FindObject (GameObject.Find("HomeScreenPanel"),"RawImage").SetActive (true);	
		FindRootObject ("TestObject").GetComponent<qrscanner3> ().enabled = true;
		FindRootObject ("ImageTarget").GetComponent<ImageTargetPlayAudio> ().enabled = false;

	}

	GameObject FindObject(GameObject parent, string name)
	{
		Component[] trs= parent.GetComponentsInChildren(typeof(Transform), true);
		foreach(Component t in trs){
			if(t.name == name){
				return t.gameObject;
			}
		}
		return null;
	}

	GameObject FindRootObject(string name)
	{
		List<GameObject> rootObjects = new List<GameObject>();
		Scene scene = SceneManager.GetActiveScene();
		scene.GetRootGameObjects( rootObjects );
		foreach(GameObject t in rootObjects){
			if(t.name == name){
				return t.gameObject;
			}
		}
		return null;
	}
}
